title: Mauro L. Castiella
theme: jekyll-theme-minimal
description: "Economist based in Buenos Aires. I hold a Bachelor and a Master's degree in Economics from Universidad Torcuato Di Tella (UTDT). My research interests lie at the intersection of macroeconomics and development, with a focus on business cycles and the role of institutions and expectations. Planning to pursue a PhD in Economics soon."

title: Mauro L. Castiella
theme: jekyll-theme-minimal
logo: /Profile.jpg

